config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :authors
  resources :food_recipes
  resources :ingredients
  resources :foods
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'food_recipes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :foodrecipes

	validates_presence_of :name
	validates_numericality_of :year
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
<% if ingredient.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% ingredient.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :quantity, class: label_class %>
          <%= form.number_field :quantity, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if ingredient.persisted? %>
<%= link_to "Cancel", ingredient, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", ingredients_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= ingredient.quantity %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit ingredient</h1>
    <% if @ingredient.persisted? %>
    <%= button_to 'Destroy', @ingredient, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', ingredient: @ingredient %>
</div>

app/views/ingredients/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Ingredients</h1>

    <%= link_to new_ingredient_path, class: button_class(theme: "primary") do %>
    Add New Ingredient
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Quantity</th>
                
      </tr>
    </thead>

    <tbody>
      <% @ingredients.each do |ingredient| %>
      <%= content_tag :tr, id: dom_id(ingredient), class: dom_class(ingredient) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to ingredient.name, ingredient %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= ingredient.quantity %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/ingredients/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New ingredient</h1>

  <%= render 'form', ingredient: @ingredient %>
</div>

app/views/ingredients/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Ingredient</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to ingredients_path, class: button_class(theme: "transparent") do %>
      All Ingredients
      <% end %>
      <%= link_to edit_ingredient_path(@ingredient), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @ingredient.name %></p>
      </li>
      <li>
        <p class="font-semibold">Quantity:</p>
        <p><%= @ingredient.quantity %></p>
      </li>
  </ul>
</div>