config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :authors
  resources :food_recipes
  resources :ingredients
  resources :foods
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'food_recipes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :food
  has_and_belongs_to_many :ingredient
  belongs_to :author



  validates_presence_of :food, :ingredient, :description, :instruction, :author
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  before_action :set_food_recipe, only: %i[ show edit update destroy ]

  # GET /food_recipes or /food_recipes.json
  def index
    @food_recipes = FoodRecipe.all
  end

  # GET /food_recipes/1 or /food_recipes/1.json
  def show
  end

  # GET /food_recipes/new
  def new
    @food_recipe = FoodRecipe.new
  end

  # GET /food_recipes/1/edit
  def edit
  end

  # POST /food_recipes or /food_recipes.json
  def create
    @food_recipe = FoodRecipe.new(food_recipe_params)

    respond_to do |format|
      if @food_recipe.save
        format.html { redirect_to food_recipe_url(@food_recipe), notice: "Food recipe was successfully created." }
        format.json { render :show, status: :created, location: @food_recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_recipes/1 or /food_recipes/1.json
  def update
    respond_to do |format|
      if @food_recipe.update(food_recipe_params)
        format.html { redirect_to food_recipe_url(@food_recipe), notice: "Food recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @food_recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_recipes/1 or /food_recipes/1.json
  def destroy
    @food_recipe.destroy

    respond_to do |format|
      format.html { redirect_to food_recipes_url, notice: "Food recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_recipe
      @food_recipe = FoodRecipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_recipe_params
      params.require(:food_recipe).permit(:food_id, :ingredient_id, :description, :instruction, :author_id)
    end
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/views/food_recipes/_food_recipe.html.erb
<div id="<%= dom_id food_recipe %>">
  <p>
    <strong>Food:</strong>
    <%= food_recipe.food_id %>
  </p>

  <p>
    <strong>Ingredient:</strong>
    <%= food_recipe.ingredient_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= food_recipe.description %>
  </p>

  <p>
    <strong>Instruction:</strong>
    <%= food_recipe.instruction %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= food_recipe.author_id %>
  </p>

</div>

app/views/food_recipes/_form.html.erb
<%= form_with(model: food_recipe) do |form| %>
<% if food_recipe.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(food_recipe.errors.count, "error") %> prohibited this food_recipe from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% food_recipe.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :food_id, class: label_class %>
          <%= form.select :food_id, options_from_collection_for_select(Food.all,'id','name',select = food_recipe.food_id), class:label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :ingredient_id, class: label_class %>
          <%= form.text_field :ingredient_id, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :description, class: label_class %>
          <%= form.text_field :description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :instruction, class: label_class %>
          <%= form.text_field :instruction, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :author_id, class: label_class %>
          <%= form.text_field :author_id, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if food_recipe.persisted? %>
<%= link_to "Cancel", food_recipe, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", food_recipes_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/food_recipes/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit food_recipe</h1>
    <% if @food_recipe.persisted? %>
    <%= button_to 'Destroy', @food_recipe, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', food_recipe: @food_recipe %>
</div>

app/views/food_recipes/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Food_recipes</h1>

    <%= link_to new_food_recipe_path, class: button_class(theme: "primary") do %>
    Add New Food recipe
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Food</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Ingredient</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Instruction</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Author</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @food_recipes.each do |food_recipe| %>
      <%= content_tag :tr, id: dom_id(food_recipe), class: dom_class(food_recipe) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= food_recipe.food.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= food_recipe.ingredient.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= food_recipe.description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= food_recipe.instruction %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= food_recipe.author.name %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', food_recipe %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/food_recipes/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New food_recipe</h1>

  <%= render 'form', food_recipe: @food_recipe %>
</div>

app/views/food_recipes/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Food_recipe</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to food_recipes_path, class: button_class(theme: "transparent") do %>
      All Food_recipes
      <% end %>
      <%= link_to edit_food_recipe_path(@food_recipe), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Food:</p>
        <p><%= @food_recipe.food.name %></p>
      </li>
      <li>
        <p class="font-semibold">Ingredient:</p>
        <p><%= @food_recipe.ingredient.name %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @food_recipe.description %></p>
      </li>
      <li>
        <p class="font-semibold">Instruction:</p>
        <p><%= @food_recipe.instruction %></p>
      </li>
      <li>
        <p class="font-semibold">Author:</p>
        <p><%= @food_recipe.author.name %></p>
      </li>
  </ul>
</div>